PIS-master/PISCoursework/Controllers/Reader/BookingsController.cs
using Microsoft.AspNetCore.Mvc;
using PISBusinessLogic;
using PISBusinessLogic.BindingModels;
using PISBusinessLogic.Interfaces;
using PISBusinessLogic.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;

namespace PISCoursework.Controllers.Reader
{
    public class BookingsController : Controller
    {
        private readonly IBookingLogic _booking;
        private readonly IBookLogic _book;
        private readonly IUserLogic _user;
        private readonly ILibraryCardLogic _libraryCard;
        private readonly IContractLogic _contract;
        private readonly IGenreLogic _genre;
        private readonly Validation validation;
        public BookingsController(IBookingLogic booking, IBookLogic book, IUserLogic user, ILibraryCardLogic libraryCard, IContractLogic contract, IGenreLogic genre)
        {
            _booking = booking;
            _book = book;
            _user = user;
            _libraryCard = libraryCard;
            _contract = contract;
            _genre = genre;
            validation = new Validation();
        }
        public ActionResult ListOfBookings()
        {
            ViewBag.Genres = _genre.Read(null);
            List<BookViewModel> books = new List<BookViewModel>();
            List<BookingViewModel> bookings = new List<BookingViewModel>();
            var Books = _book.Read(null);
            var Bookings = _booking.Read(null);
            var card = _libraryCard.Read(new LibraryCardBindingModel
            {
                UserId = Program.Reader.Id
            }).FirstOrDefault();
            foreach (var booking in Bookings)
            {
                if (booking.DateTo >= DateTime.Now)
                {
                    if (booking.LibraryCardId == card.Id)
                    {
                        bookings.Add(booking);
                    }
                }
                else
                {
                    _booking.Delete(new BookingBindingModel
                    {
                        Id = booking.Id
                    });
                }
            }
            foreach (var book in Books)
            {
                foreach (var b in bookings)
                {
                    if (book.Id == b.BookId)
                    {
                        books.Add(book);
                    }
                }
            }        
            ViewBag.Books = books;
            return View("Views/Reader/ListOfBookings.cshtml");
        }
        public IActionResult AddBooking(int id)
        {
            ViewBag.BookId = id;
            return View("Views/Reader/AddBooking.cshtml");
        }

        [HttpPost]
        public ActionResult AddBooking( BookingBindingModel model)
        {
            ViewBag.BookId = model.Id;
            if (validation.bookingValidation(model)!="")
            {
                ViewBag.Booking = _booking.Read(null);
                ModelState.AddModelError("", validation.bookingValidation(model));
                return View("Views/Reader/AddBooking.cshtml");
            }
           
            var libraryCard = _libraryCard.Read(new LibraryCardBindingModel
            {
                UserId = Program.Reader.Id
            }).FirstOrDefault();
            if (Convert.ToInt32(libraryCard.Year) < DateTime.Now.Year)
            {
                ViewBag.Booking = _booking.Read(null);
                ModelState.AddModelError("","Ваш читательский билет просрочен, обратитесь в библиотеку");
                return View("Views/Reader/AddBooking.cshtml");
            }
            _booking.CreateOrUpdate(new BookingBindingModel
            {
                DateFrom = model.DateFrom,
                DateTo = model.DateTo,
                BookId = model.BookId,
                LibraryCardId = libraryCard.Id
            });
            var book = _book.Read(new BookBindingModel
            {
                Id = model.BookId
            }).FirstOrDefault();
            if (book.Status == Status.Свободна)
            {
                _book.CreateOrUpdate(new BookBindingModel
                {
                    Id = book.Id,
                    PublishingHouse = book.PublishingHouse,
                    Author = book.Author,
                    Year = book.Year,
                    GenreId = book.GenreId,
                    Name = book.Name,
                    Status = Status.Забронирована
                });
            }
            return RedirectToAction("ListOfBookings");
        }
    }
}

PIS-master/PISCoursework/Controllers/Reader/BooksReaderController.cs
using Microsoft.AspNetCore.Mvc;
using PISBusinessLogic;
using PISBusinessLogic.BindingModels;
using PISBusinessLogic.BusinessLogic;
using PISBusinessLogic.Interfaces;
using PISBusinessLogic.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;

namespace PISCoursework.Controllers.Reader
{
    public class BooksReaderController : Controller
    {
        private readonly IBookLogic _book;
        private readonly IGenreLogic _genre;
        private readonly IUserLogic _user;
        private readonly ILibraryCardLogic _libraryCard;
        private readonly IContractLogic _contract;
        private readonly IBookingLogic _booking;
        private Validation validation;
        private readonly ReportLogic _report;
        public BooksReaderController(IBookLogic book, IGenreLogic genre, IUserLogic user, ILibraryCardLogic libraryCard, IContractLogic contract, ReportLogic report, IBookingLogic booking)
        {
            _book = book;
            _genre = genre;
            _user = user;
            _libraryCard = libraryCard;
            _contract = contract;
            _report = report;
            _booking = booking;
            validation = new Validation();
        }

        [HttpGet]
        public ActionResult ListOfBooksReader(BookBindingModel model)
        {
            ViewBag.Genres = _genre.Read(null);
            ViewBag.Books = _book.Read(new BookBindingModel
            {
                Status = Status.Свободна
            });
            return BookSearch(model);

        }        
        public ActionResult BookSearch(BookBindingModel model)
        {
            ViewBag.Genres = _genre.Read(null);
            var freebooks = _book.Read(null);
            var Bookings = _booking.Read(null);
            List<BookingViewModel> bookings = new List<BookingViewModel>();
            List<BookViewModel> books = new List<BookViewModel>();
            var card = _libraryCard.Read(new LibraryCardBindingModel
            {
                UserId = Program.Reader.Id
            }).FirstOrDefault();
            List<BookViewModel> freeBooks = new List<BookViewModel>();
            foreach (var booking in Bookings)
            {
                var b = _book.Read(new BookBindingModel
                {
                    Id = booking.BookId
                }).FirstOrDefault();
                if (booking.DateTo < DateTime.Now)
                {
                    _book.CreateOrUpdate(new BookBindingModel
                    {
                        Id = b.Id,
                        Name = b.Name,
                        PublishingHouse = b.PublishingHouse,
                        Author = b.Author,
                        Year = b.Year,
                        GenreId = b.GenreId,
                        Status = Status.Свободна
                    });
                }
                if (booking.LibraryCardId == card.Id)
                {
                    bookings.Add(booking);
                }
            }
            foreach (var book in freebooks)
            {
                foreach (var b in bookings)
                {
                    if (book.Id == b.BookId)
                    {
                        books.Add(book);
                    }
                }
            }          
            freeBooks = freebooks;
            foreach (var b in books)
            {
                freeBooks.Remove(b);
            }
            ViewBag.Books = freeBooks;
            List<BookViewModel> removebooks = new List<BookViewModel>();
            //по названию
            if (model.Name != null && model.GenreId == 0 && model.Author == null)
            {
                foreach (var el in freeBooks)
                {
                    if (el.Name != model.Name)
                    {
                        removebooks.Add(el);
                    }
                }
                foreach (var book in removebooks)
                {
                    freeBooks.Remove(book);
                }
                ViewBag.Books = freeBooks;
                return View("Views/Reader/ListOfBooksReader.cshtml");
            }
            //по жанру
            if (model.GenreId != 0 && model.Name == null && model.Author == null)
            {
                foreach (var el in freeBooks)
                {
                    if (el.GenreId != model.GenreId)
                    {
                        removebooks.Add(el);
                    }
                }
                foreach (var book in removebooks)
                {
                    freeBooks.Remove(book);
                }
                ViewBag.Books = freeBooks;
                return View("Views/Reader/ListOfBooksReader.cshtml");
            }
            //по автору
            if (model.GenreId == 0 && model.Name == null && model.Author != null)
            {
                foreach (var el in freeBooks)
                {
                    if (el.Author != model.Author)
                    {
                        removebooks.Add(el);
                    }
                }
                foreach (var book in removebooks)
                {
                    freeBooks.Remove(book);
                }
                ViewBag.Books = freeBooks;
                return View("Views/Reader/ListOfBooksReader.cshtml");
            }
            //по жанру и названию
            if (model.GenreId != 0 && model.Name != null && model.Author == null)
            {
                foreach (var el in freeBooks)
                {
                    if (el.GenreId != model.GenreId || el.Name != model.Name)
                    {
                        removebooks.Add(el);
                    }
                }
                foreach (var book in removebooks)
                {
                    freeBooks.Remove(book);
                }
                ViewBag.Books = freeBooks;
                return View("Views/Reader/ListOfBooksReader.cshtml");
            }
            // по всем трем
            if (model.GenreId != 0 && model.Name != null && model.Author != null)
            {
                foreach (var el in freeBooks)
                {
                    if (el.GenreId != model.GenreId || el.Name != model.Name || el.Author != model.Author)
                    {
                        removebooks.Add(el);
                    }
                }
                foreach (var book in removebooks)
                {
                    freeBooks.Remove(book);
                }
                ViewBag.Books = freeBooks;
                return View("Views/Reader/ListOfBooksReader.cshtml");
            }
            //по жанру и автору
            if (model.GenreId != 0 && model.Name == null && model.Author != null)
            {
                foreach (var el in freeBooks)
                {
                    if (el.GenreId != model.GenreId || el.Author != model.Author)
                    {
                        removebooks.Add(el);
                    }
                }
                foreach (var book in removebooks)
                {
                    freeBooks.Remove(book);
                }
                ViewBag.Books = freeBooks;
                return View("Views/Reader/ListOfBooksReader.cshtml");
            }
            //по автору и названию
            if (model.GenreId == 0 && model.Name != null && model.Author != null)
            {
                foreach (var el in freeBooks)
                {
                    if (el.Name != model.Name || el.Author != model.Author)
                    {
                        removebooks.Add(el);
                    }
                }
                foreach (var book in removebooks)
                {
                    freeBooks.Remove(book);
                }
                ViewBag.Books = freeBooks;
                return View("Views/Reader/ListOfBooksReader.cshtml");
            }
            if (validation.bookSearch(model))
            {
                ModelState.AddModelError("", "Выберите хотя бы один параметр поиска");
                return View("Views/Reader/ListOfBooksReader.cshtml");
            }
            return View("Views/Reader/ListOfBooksReader.cshtml");
        }         
    }
}

PIS-master/PISCoursework/Views/Reader/AddBooking.cshtml
@model PISBusinessLogic.BindingModels.BookingBindingModel

@{
    ViewData["Title"] = "Бронирование";
}
<div class="text-left text-black-50">
    <h1>@ViewData["Title"]</h1>
</div>


<p>Задайте период бронирования</p>
@using (Html.BeginForm("AddBooking", "Bookings", FormMethod.Post))
{
    <p>
        <div class="col-sm-8">
            Дата начала бронирования:<br>
            <input type="date" name="DateFrom" />
        </div>
        <div class="col-sm-8">
            Дата окончания бронирования:<br>
            <input type="date" name="DateTo" />
        </div>
        <input type="hidden" value="@ViewBag.BookId" name="BookId" />
        @Html.ValidationSummary(true, "", new { @style = "color: black" })
        <br />
        <div class="col-sm-8">
            <input type="submit" value="Сохранить" class="btn btn-dark btn-sm" />
        </div>

    </p>

}

PIS-master/PISCoursework/Views/Reader/ChangeDate.cshtml
@model PISBusinessLogic.BindingModels.BookBindingModel
@{
    ViewData["Title"] = "Изменение даты возврата";
}
@Html.ValidationSummary()
<div class="text-center text-black-50">
    <h1>Изменение даты возврата</h1>
</div>
@if (ViewBag.ContractBooks != null)
{
    <p>Номер: @ViewBag.ContractBooks.Id</p>
    <p>Дата: @ViewBag.ContractBooks.Date.ToShortDateString()</p>
    <p>Дата возврата книг: @ViewBag.ContractBooks.DateReturn.ToShortDateString()</p>
    <p>Стоимость: @ViewBag.ContractBooks.Sum</p>
    <table class="table">
        <tr>
            <td>Название</td>
            <td>Автор</td>
            <td>Жанр</td>
            <td>Издательство</td>
            <td>Год издания</td>
        </tr>
        @foreach (var genre in ViewBag.Genres)
        {
            @foreach (var book in ViewBag.ContractBooks.ContractBooks)
            {
                @if (genre.Id == book.GenreId)
                {

                    <tr>
                        <td>@book.Name</td>
                        <td>@book.Author</td>
                        <td>@genre.Name</td>
                        <td>@book.PublishingHouse</td>
                        <td>@book.Year</td>
                    </tr>
                }
            }
        }
    </table>
    <hr/>
<form asp-controller="Contract" asp-action="ChangeDate" method="get">
    <p>Измените дату возврата</p>
    <div class="col-sm-8">
        Дата возврата:<br>
        <input type="date" name="date" />
    </div>
    <br />
    <input type="hidden" value="@ViewBag.ContractBooks.Id" name="id" />
    <div class="form-group row">
        <div class="col-sm-8">
            <input type="submit" value="Изменить дату возврата" class="btn btn-dark btn-sm" />
        </div>
    </div>
    @Html.ValidationSummary(true, "", new { @style = "color: black" })
</form>
}

PIS-master/PISCoursework/Views/Reader/ListOfBookings.cshtml
@{
    ViewData["Title"] = "Забронированные книги";
}
<div class="text-center text-black-50">
    <h1>Забронированные книги</h1>
</div>
<hr />
    <table class="table">
        <tr>
            <td>Название</td>
            <td>Автор</td>
            <td>Жанр</td>
            <td>Издательство</td>
            <td>Год издания</td>
            <td>Цена проката, руб./день</td>
        </tr>
        @foreach (var genre in ViewBag.Genres)
        {
            @foreach (var book in ViewBag.Books)
            {
                @if (genre.Id == book.GenreId)
                {

                    <tr>
                        <td>@book.Name</td>
                        <td>@book.Author</td>
                        <td>@genre.Name</td>
                        <td>@book.PublishingHouse</td>
                        <td>@book.Year</td>
                        <td>@genre.Price</td>
                    </tr>
                }
            }
        }
    </table>

PIS-master/PISCoursework/Views/Reader/ListOfBooksReader.cshtml
@model PISBusinessLogic.BindingModels.BookBindingModel
@{
    ViewData["Title"] = "Список книг";
}

<div class="text-center text-black-50">
    <h1>Список книг</h1>
</div>
<hr />
<strong> <a class="btn btn-dark btn-sm" href="/Bookings/ListOfBookings">Просмотреть список забронированных книг</a></strong>
<hr />
<form asp-controller="BooksReader" asp-action="ListOfBooksReader" method="get">
    <div class="form-group row">
        <label class="col-sm-2 col-form-label">По названию:</label>
        <div class="col-sm-4">
            @Html.TextBoxFor(x => x.Name)
            <br />
        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-2 col-form-label">По автору:</label>
        <div class="col-sm-4">
            @Html.TextBoxFor(x => x.Author)
            <br />
        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-2 col-form-label">По жанру:</label>
        <div class="col-sm-4">
            <select class="custom-select" name="GenreId" id="GenreId">
                <option value="" selected disabled hidden>Выберите жанр</option>
                @foreach (PISBusinessLogic.ViewModels.GenreViewModel genre in ViewBag.Genres)
                {
                    <option value="@genre.Id">@genre.Name</option>
                }
            </select>
        </div>
    </div>
    <br />
    <div class="form-group row">
        <div class="col-sm-4">
            <input type="submit" value="Найти" class="btn btn-dark" />
            <hr />
        </div>
    </div>
</form>
<table class="table">
    <tr>
        <td>Название</td>
        <td>Автор</td>
        <td>Жанр</td>
        <td>Издательство</td>
        <td>Год издания</td>
        <td>Цена проката, руб./день</td>
        <td>Статус</td>
        <td>Забронировать</td>
    </tr>
    @foreach (var genre in ViewBag.Genres)
    {
        @foreach (var book in ViewBag.Books)
        {
            @if (genre.Id == book.GenreId)
            {

                <tr>
                    <td>@book.Name</td>
                    <td>@book.Author</td>
                    <td>@genre.Name</td>
                    <td>@book.PublishingHouse</td>
                    <td>@book.Year</td>
                    <td>@genre.Price</td>
                    <td>@book.Status</td>
                    <td>
                        @Html.ActionLink("Забронировать", "AddBooking", "Bookings", new { id = @book.Id }, new { @class = "btn btn-dark btn-sm" })
                    </td>
                </tr>
            }
        }
    }
</table>

PIS-master/PISCoursework/Views/Reader/ListOfContractsReader.cshtml
@{
    ViewData["Title"] = "Договоры";
}

<div class="text-center text-black-50">
    <h1>Договоры</h1>
</div>
<p>ФИО читателя: @ViewBag.Users.FIO</p>
@foreach (var contract in ViewBag.Contracts)
{
    <p>Номер: @contract.Id</p>
    <p>Дата: @contract.Date.ToShortDateString()</p>
    <p>Дата возврата книг: @contract.DateReturn.ToShortDateString()</p>
    <p>Стоимость: @contract.Sum</p>
    <p>Штраф: @contract.Fine</p>
    <p>Статус: @contract.ContractStatus</p>
    <table class="table">
        <tr>
            <td>Название</td>
            <td>Автор</td>
            <td>Жанр</td>
            <td>Издательство</td>
            <td>Год издания</td>
        </tr>
        @foreach (var genre in ViewBag.Genres)
        {
            @foreach (var book in @contract.ContractBooks)
            {
                @if (genre.Id == book.GenreId)
                {

                    <tr>
                        <td>@book.Name</td>
                        <td>@book.Author</td>
                        <td>@genre.Name</td>
                        <td>@book.PublishingHouse</td>
                        <td>@book.Year</td>
                    </tr>
                }
            }
        }
    </table>
    <hr />
    <strong> <a class="btn btn-dark btn-sm" href="/Contract/ChangeDate/@contract.Id">Изменить дату возврата</a></strong>
    <hr />
    <strong> <a class="btn btn-dark btn-sm" href="/Contract/PrintContract/@contract.Id">Сохранить в формате docx</a></strong>
}