PIS-master/PISCourseworkARMAccountant/Controllers/Accountant/AccountantController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using PISBusinessLogic.BindingModels;
using PISBusinessLogic.Interfaces;
using PISBusinessLogic.Enums;
using PISBusinessLogic.ViewModels;
using PISBusinessLogic.BusinessLogic;

namespace PISCourseworkARMAccountant.Controllers
{
    public class AccountantController : Controller
    {
        private readonly IContractLogic _contract;
        private readonly IUserLogic _user;
        private readonly ReportLogic _report;
        private Validation validation;
        public AccountantController(IUserLogic user, IContractLogic contract, ReportLogic report)
        {
            _user = user;
            _contract = contract;
            _report = report;
            validation = new Validation();
        }
       
        public ActionResult ChangeCommission(int Id, string ComissionPercent)
        {

            if (validation.сhangeCommission(Id, ComissionPercent))
            {
                ViewBag.Users = _user.Read(null);
                var user = _user.Read(new UserBindingModel
                {
                    Id = Id
                }).FirstOrDefault();
                decimal percent = decimal.Parse(ComissionPercent.Replace('.', ',')) / 10000;
                decimal salary =decimal.Parse(user.Salary.ToString());
                _user.CreateOrUpdate(new UserBindingModel
                {
                    Id = Id,
                    FIO = user.FIO,
                    Password = user.Password,
                    Email = user.Email,
                    Salary = user.Salary,
                    Comission = (Math.Round(Convert.ToDouble(salary * percent), 2)).ToString(),
                    ComissionPercent = ComissionPercent,
                });
                ModelState.AddModelError("", "Процент успешно изменен");
                return View("Views/Accountant/ChangeCommission.cshtml");
            }
            else
            {
                ViewBag.Users = _user.Read(null);
                ModelState.AddModelError("", "Выберите библиотекаря или процент");
                return View("Views/Accountant/ChangeCommission.cshtml");
            }
        }
        public ActionResult ChangeCommissionAll(string ComissionPercentAll)
        {
            if (validation.сhangeCommissionAll(ComissionPercentAll))
            {
                var user = _user.Read(null);
                ViewBag.Users = _user.Read(null);
                List<UserViewModel> users = new List<UserViewModel>();
                foreach (var us in user)
                {
                    if (us.Role == Roles.Библиотекарь)
                    {
                        decimal percent = decimal.Parse(ComissionPercentAll.Replace('.', ',')) / 10000;
                        decimal salary = decimal.Parse(us.Salary.ToString());
                        _user.CreateOrUpdate(new UserBindingModel
                        {
                            Id = us.Id,
                            FIO = us.FIO,
                            Password = us.Password,
                            Email = us.Email,
                            Salary = us.Salary,
                            Comission = (Math.Round(Convert.ToDouble(salary * percent), 2)).ToString(),
                            ComissionPercent = ComissionPercentAll,
                        });
                    }
                }
                ModelState.AddModelError("", "Процент успешно изменен");
                return View("Views/Accountant/ChangeCommission.cshtml");
            }
            else
            {
                ViewBag.Users = _user.Read(null);
                ModelState.AddModelError("", "Введите процент");
                return View("Views/Accountant/ChangeCommission.cshtml");
            }
        }
        public ActionResult ListContract(int Id, DateTime month)
        {
            if (validation.listContract(Id, month))
            {
                int month1 = month.Month;
                List<ContractViewModel> contracts = new List<ContractViewModel>();
                var contract = _contract.Read(new ContractBindingModel
                {
                    LibrarianId = Id
                });
                foreach (var cont in contract)
                {
                    if (cont.Date.Month == month1)
                    {
                        contracts.Add(cont);
                    }
                }
                contracts.OrderBy(x => x.Date);
                ViewBag.Contract = contracts;
                ViewBag.Users = _user.Read(null);
                return View("Views/Accountant/ListContract.cshtml");
            }
            else
            {
                ViewBag.Users = _user.Read(null);
                ModelState.AddModelError("", "Выберите библиотекаря и дату");
                return View("Views/Accountant/ListContract.cshtml");
            }

        }
        public ActionResult ListOfLibrarian(UserBindingModel model)
        {
            var user = _user.Read(null);
            List<UserViewModel> users = new List<UserViewModel>();
            foreach (var us in user)
            {
                if (us.Role == Roles.Библиотекарь)
                    users.Add(us);
            }
            ViewBag.Users = users;
            return LibrarianSearch(model);
        }
        public ActionResult LibrarianSearch(UserBindingModel model)
        {
            var user = _user.Read(null);
            List<UserViewModel> users = new List<UserViewModel>();
            foreach (var us in user)
            {
                if (us.Role == Roles.Библиотекарь)
                    users.Add(us);
            }
            ViewBag.Users = users;

            LibrarianSearchCode(model);
            LibrarianSearchFIO(model);
            LibrarianSearchCodeAndFIO(model);
           
            if (model.FIO == null && model.Id == null)
            {
                ModelState.AddModelError("", "Необходимо ввести хотя бы один параметр поиска");
                return View("Views/Accountant/ListOfLibrarian.cshtml");
            }
            return View(model);
        }
        public ActionResult LibrarianSearchCode(UserBindingModel model)
        {
            //по личному коду
            if (model.FIO == null && model.Id != null)
            {
                var Users = _user.Read(new UserBindingModel
                {
                    FIO = model.FIO,
                    Id = model.Id
                });
                List<UserViewModel> librarians = new List<UserViewModel>();
                foreach (var User in Users)
                {
                    if (User.Role == Roles.Библиотекарь)
                    {
                        librarians.Add(User);
                    }
                }
                ViewBag.Users = librarians;
                return View("Views/Accountant/ListOfLibrarian.cshtml");
            }
            return View(model);
        }
        public ActionResult LibrarianSearchFIO(UserBindingModel model)
        {
            //по ФИО
            if (model.FIO != null && model.Id == null)
            {
                var Users = _user.Read(new UserBindingModel
                {
                    FIO = model.FIO,
                    Id = model.Id
                });
                List<UserViewModel> librarians = new List<UserViewModel>();
                foreach (var User in Users)
                {
                    if (User.Role == Roles.Библиотекарь)
                    {
                        librarians.Add(User);
                    }
                }
                ViewBag.Users = librarians;
                return View("Views/Accountant/ListOfLibrarian.cshtml");
            }
            return View(model);
        }
        public ActionResult LibrarianSearchCodeAndFIO(UserBindingModel model)
        {
            //по ФИО и личному коду
            if (model.FIO != null && model.Id != null)
            {
                var Users = _user.Read(new UserBindingModel
                {
                    FIO = model.FIO
                });
                List<UserViewModel> librarians = new List<UserViewModel>();
                foreach (var User in Users)
                {
                    if (User.Role == Roles.Библиотекарь)
                    {
                        if (User.Id == model.Id)
                        {
                            librarians.Add(User);
                        }
                    }
                }
                ViewBag.Users = librarians;
                return View("Views/Accountant/ListOfLibrarian.cshtml");
            }
            return View(model);
        }
    }
}

PIS-master/PISCourseworkARMAccountant/Controllers/Accountant/SalaryController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using PISBusinessLogic.BindingModels;
using PISBusinessLogic.BusinessLogic;
using PISBusinessLogic.Interfaces;

namespace PISCourseworkARMAccountant.Controllers.Accountant
{
    public class SalaryController : Controller
    {
        private readonly IUserLogic _user;
        private readonly IPaymentLogic _payment;
        private Validation validation;
        public SalaryController(IUserLogic user, IPaymentLogic payment)
        {
            _user = user;
            _payment = payment;
            validation = new Validation();
        }
        public ActionResult AddSalary(PaymentBindingModel model, int Id)
        {
            var pay = _payment.Read(new PaymentBindingModel
            {
                UserId = Id
            });
            foreach (var p in pay)
            {
                if (p.Date.Month == model.Date.Month && p.Date.Year == model.Date.Year)
                {
                    ViewBag.Users = _user.Read(null);
                    ModelState.AddModelError("", "В этом месяце уже начислена зарплата");
                    return View("Views/Accountant/Salary.cshtml");
                }
            }
            if (validation.addSalar(model, Id))
            {
                ViewBag.Users = _user.Read(null);
                var user = _user.Read(new UserBindingModel
                {
                    Id = Id
                }).FirstOrDefault();
                string str = user.Salary.ToString();
                str = str.Replace(",", ".");
                decimal salary = decimal.Parse(str);
                decimal com = decimal.Parse(user.Comission);
                decimal sum = salary + com;
                _payment.CreateOrUpdate(new PaymentBindingModel
                {
                    Date = model.Date,
                    Sum = Math.Round(Convert.ToDouble(sum), 2),
                    UserId = Id,
                });
                ModelState.AddModelError("", "Зарплата начислена");
                return View("Views/Accountant/Salary.cshtml");
            }
            else
            {
                ViewBag.Users = _user.Read(null);
                ModelState.AddModelError("", "Выберите библиотекаря или поставьте дату");
                return View("Views/Accountant/Salary.cshtml");
            }
        }
        public ActionResult CheckSalary(PaymentBindingModel model, string sum)
        {
            ViewBag.Users = _user.Read(null);
            if (validation.checkSalary(model,sum))
            {
                var pay = _payment.Read(new PaymentBindingModel
                {
                    UserId = model.UserId
                });
                foreach (var p in pay)
                {
             
                    if (p.Date.Month == model.Date.Month && p.Date.Year == model.Date.Year)
                    {
                        if (p.Sum < Convert.ToDouble(sum))
                        {
                            ModelState.AddModelError("", "Сумма превышает суммы платежа");
                            return View("Views/Accountant/LeadSalary.cshtml");
                        }
                        _payment.CreateOrUpdate(new PaymentBindingModel
                        {
                            Id = p.Id,
                            Date = p.Date,
                            Sum = p.Sum - Convert.ToDouble(sum),
                            UserId = p.UserId
                        });
                        ModelState.AddModelError("", "Изменено");
                        return View("Views/Accountant/LeadSalary.cshtml");
                    }
                }
                ModelState.AddModelError("", "Нет платежа по такому параметру");
                return View("Views/Accountant/LeadSalary.cshtml");
            }
            else
            {
                ModelState.AddModelError("", "Выберите библиотекаря, дату и введите сумму");
                return View("Views/Accountant/LeadSalary.cshtml");
            }
        }
        public ActionResult CheckSalaryAll(DateTime date)
        {
            var pay = _payment.Read(null);
            double sum = 0;
            if (!validation.salaryAll(date))
            {
                foreach (var p in pay)
                {
                    int year = (p.Date).Year;
                    int year1 = date.Year;
                    if (year == year1)
                    {
                        sum += Math.Round(Convert.ToDouble(p.Sum), 2);
                    }
                }
            }
            else
            {
                ViewBag.Users = _user.Read(null);
                ModelState.AddModelError("", "Выберите дату");
                return View("Views/Accountant/Salary.cshtml");
            }
            ViewBag.Sum = Math.Round(sum, 2);
            ViewBag.Users = _user.Read(null);
            return View("Views/Accountant/Salary.cshtml");
        }
        public ActionResult SalaryAll(DateTime date)
        {
            return CheckSalaryAll(date);  
        }
    }
}

PIS-master/PISCourseworkARMAccountant/Views/Accountant/ChangeCommission.cshtml
@{
    ViewData["Title"] = "Изменение процента комиссионных";
}


<form asp-controller="Accountant" asp-action="ChangeCommission">

    @Html.ValidationSummary(true, "", new { @style = "color: black" })
    <div class="text-center text-black-50">
        <h3>Процент комиссионных</h3>
    </div>
    <hr />
    <div class="form-group row">
        <label class="col-sm-2 col-form-label">Библиотекарь:</label>
        <div class="col-sm-4">
            <select class="custom-select custom-select-sm" name="Id" id="Id">
                <option value="" selected disabled hidden>Выберите библиотекаря</option>
                @foreach (PISBusinessLogic.ViewModels.UserViewModel user in ViewBag.Users)
                {
                    if (@user.Role == 0)
                    {
                        <option value="@user.Id">@user.FIO</option>
                    }
                }
            </select>
        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-2 col-form-label">Комиссионный процент:</label>
        <div class="col-sm-4">
            <input type="number" value="" step="0.1" min="0" max="10" name="ComissionPercent" />
        </div>
    </div>

    <div class="form-group row">
        <input type="submit" value="Изменить" class="btn btn-dark btn-sm" />

    </div>
</form>
<form asp-controller="Accountant" asp-action="ChangeCommissionAll">
    <div class="text-center text-black-50">
        <h3>Процент комиссионных для всех</h3>
    </div>
    <hr />
    <div class="form-group row">
        <label class="col-sm-2 col-form-label">Комиссионный процент:</label>
        <div class="col-sm-4">
            <input type="number" value="" step="0.1" min="0" max="10" name="ComissionPercentAll" />
        </div>
    </div>
    <div class="form-group row">
        <input type="submit" value="Изменить для всех" class="btn btn-dark btn-sm" />
    </div>
</form>

PIS-master/PISCourseworkARMAccountant/Views/Accountant/Chart.cshtml
<title>@ViewData["Title"] Диаграмма</title>
<div class="text-center text-black-50">
    <h1>Диаграмма</h1>
</div>
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.5/jspdf.min.js"></script>

<div id="chart_div"></div>
<input type="submit" id="save-pdf" class="btn btn-dark btn-sm" value="сохранить в pdf" />
<script type="text/javascript">


    google.charts.load('current', {
        packages: ['corechart', 'bar']
    });
    google.charts.setOnLoadCallback(LoadData);

    function LoadData() {
        $.ajax({

            url: './Charts',
            dataType: "json",
            type: "GET",
            error: function(xhr, status, error) {
                var err = eval("(" + xhr.responseText + ")");
                toastr.error(err.message);
            },
            success: function(data) {
                PopulationChart(data);
                return false;
            }
        });
        return false;
    }

    function PopulationChart(data) {
        var dataArray = [
            ['userFIO','Sum']
        ];
        $.each(data, function(i, item) {
            dataArray.push([item.userFIO, item.sum]);
        });
        var data = google.visualization.arrayToDataTable(dataArray);
        var options = {
            title: 'Cтоимость заключенных договоров @DateTime.Now.ToShortDateString() ',
            chartArea: {
                width: '50%'
            },
            colors: ['#17a2b8'],
            hAxis: {
                title: 'Библиотекарь',
                minValue: 0
            },
            vAxis: {
                title: 'Сумма'
            }
        };
        var chart = new google.visualization.ColumnChart(document.getElementById('chart_div'));
        var btnSave = document.getElementById('save-pdf');
        chart.draw(data, options);
        btnSave.addEventListener('click', function () {
            var doc = new jsPDF('l');
            doc.addImage(chart.getImageURI(), 0, 0);
            doc.save('Диаграмма стоимость заключенных договоров.pdf');
        }, false);
        return false;
    }
</script>  

PIS-master/PISCourseworkARMAccountant/Views/Accountant/CheckLibrarian.cshtml
@model PISBusinessLogic.BindingModels.UserBindingModel
<div class="text-center text-black-50">
    <h3>Проверка отчета библиотекаря</h3>
</div>
<hr />
@using (Html.BeginForm("CheckLibrarian", "Report"))
{
    <p>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Библиотекарь:</label>
            <div class="col-sm-4">
                <select class="custom-select custom-select-sm" name="Id" id="Id">
                    <option value="" selected disabled hidden>Выберите библиотекаря:</option>
                    @foreach (PISBusinessLogic.ViewModels.UserViewModel user in ViewBag.Users)
                    {
                        if (@user.Role == 0)
                        {
                            <option value="@user.Id">@user.FIO</option>
                        }
                    }
                </select>
            </div>
        </div>
        <div class="col-sm-4">
            Количество договоров по отчету:
            <input id="CountReport" name="CountReport" />
        </div>
        <div class="col-sm-8" style="margin-top: 15px">
            <input type="submit" value="Найти" class="btn btn-dark btn-sm" />
        </div>
    </p>
}
@Html.ValidationSummary(true, "", new { @style = "color: black" })

PIS-master/PISCourseworkARMAccountant/Views/Accountant/DistributionSalary.cshtml
@{
    ViewData["Title"] = "Распределение зарплаты библиотекарей по месяцам";
}
<div class="text-center text-black-50">
    <h3>Распределение зарплаты библиотекарей по месяцам</h3>
</div>
<hr />
<form asp-controller="Report" asp-action="DistributionSalary">
    <div class="col-sm-8">
        Дата:<br>
        <input type="date" name="date" />
    </div>
    <br />
    <div class="col-sm-8">
        <input type="submit" value="Вывести" class="btn btn-dark btn-sm" />
    </div>
</form>
@Html.ValidationSummary(true, "", new { @style = "color: black" })
@if (ViewBag.Librarians != null && ViewBag.Sum != null)
{
    <table class="table">
        <tr>
            <td>Библиотекарь</td>
            <td>Январь</td>
            <td>Февраль</td>
            <td>Март</td>
            <td>Апрель</td>
            <td>Май</td>
            <td>Июнь</td>
            <td>Июль</td>
            <td>Август</td>
            <td>Сентябрь</td>
            <td>Октябрь</td>
            <td>Ноябрь</td>
            <td>Декабрь</td>
        </tr>
        @foreach (var r in ViewBag.Librarians)
        {
            @foreach (var i in ViewBag.Sum)
            {
                @foreach (var k in i)
                {
                    if (k.Key == r.Id)
                    {
                        <tr>
                            <td>@r.FIO</td>

                            <td>@k.Value.Item1</td>

                            <td>@k.Value.Item2</td>

                            <td>@k.Value.Item3</td>

                            <td>@k.Value.Item4</td>

                            <td>@k.Value.Item5</td>

                            <td>@k.Value.Item6</td>

                            <td>@k.Value.Item7.Item1</td>

                            <td>@k.Value.Item7.Item2</td>

                            <td>@k.Value.Item7.Item3</td>

                            <td>@k.Value.Item7.Item4</td>

                            <td>@k.Value.Item7.Item5</td>

                            <td>@k.Value.Item7.Item6</td>
                        </tr>
                    }
                }
            }
        }

    </table>
}

PIS-master/PISCourseworkARMAccountant/Views/Accountant/LeadSalary.cshtml
@model PISBusinessLogic.BindingModels.PaymentBindingModel
@{
    ViewData["Title"] = "Ведомость заработной платы";
}


<form asp-controller="Salary" asp-action="CheckSalary">
    <div class="text-center text-black-50">
        <h3>Изменение платежа библиотекаря</h3>
    </div>
    <div class="form-group row">
        <label class="col-sm-2 col-form-label">Библиотекарь:</label>
        <div class="col-sm-4">
            <select class="custom-select custom-select-sm" name="UserId" id="UserId">
                <option value="" selected disabled hidden>Выберите библиотекаря</option>
                @foreach (PISBusinessLogic.ViewModels.UserViewModel user in ViewBag.Users)
                {
                    if (@user.Role == 0)
                    {
                        <option value="@user.Id">@user.FIO</option>
                    }
                }
            </select>
        </div>
    </div>
    <div class="col-sm-8">
        Дата:<br>
        <input type="date" name="date" />
    </div>
    <div class="col-sm-8">
        Сумма:<br>
        <input type="number" value="" step="0.01" min="0" name="sum" id="sum" /><br>
    </div>
    <div class="col-sm-8">
        <input type="submit" value="Изменить" class="btn btn-dark btn-sm" />
    </div>
</form>
 @Html.ValidationSummary(true, "", new { @style = "color: black" })
<form asp-controller="Report" asp-action="LeadSalary">
    <div class="text-center text-black-50">
        <h3>Ведомость заработной платы</h3>
    </div>
    <hr />
    <div class="col-sm-8">
        Дата:<br>
        <input type="month" name="month" />
    </div>
    <br />
    <div class="col-sm-8">
        <input type="submit" value="Сформировать" class="btn btn-dark btn-sm" />
    </div>
</form>
<br />
<div class="col-sm-8">
    <input type="button" id="btnExport" class="btn btn-dark btn-sm" value="Сохранить в pdf" onclick="Export()" />
</div>
<div id="tbl">
    @if (ViewBag.Payment != null)
    {
        <div class="text-center text-black-50">
            <h3>Ведомость заработной платы за @ViewBag.Month.Month месяц @ViewBag.Month.Year год</h3>
        </div>
        <table class="table">
            <tr>
                <td>Номер платежа</td>
                <td>ФИО библиотекаря</td>
                <td>Сумма, руб.</td>
                <td>Подпись</td>
            </tr>
            @foreach (var r in ViewBag.Payment)
            {
                foreach (var u in ViewBag.Users)
                {
                    if (r.UserId == u.Id)
                    {
                        <tr>
                            <td>@r.Id</td>

                            <td>@u.FIO</td>

                            <td>@r.Sum</td>
                        </tr>
                    }

                }
            }
        </table>
        <p><strong>Итого: @ViewBag.Sum</strong></p>
    }
</div>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.22/pdfmake.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/0.4.1/html2canvas.min.js"></script>
<script type="text/javascript">
    function Export() {
        html2canvas(document.getElementById('tbl'), {
            onrendered: function (canvas) {
                var data = canvas.toDataURL();
                var docDefinition = {
                    content: [{
                        image: data,
                        width: 500
                    }]
                };
                pdfMake.createPdf(docDefinition).download("Ведомость.pdf");
            }
        });
    }
</script>

PIS-master/PISCourseworkARMAccountant/Views/Accountant/ListContract.cshtml
@model PISBusinessLogic.BindingModels.ContractBindingModel
@{
    ViewData["Title"] = "Выборка данных о договорах";
}
<div class="text-center text-black-50">
    <h1>Выборка данных о договорах</h1>
</div>
<hr />
<form asp-controller="Accountant" asp-action="ListContract" method="get">
    <div class="col-sm-8">
        <p>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Библиотекарь:</label>
                <div class="col-sm-4">
                    <select class="custom-select custom-select-sm" name="Id" id="Id">
                        <option value="" selected disabled hidden>Выберите библиотекаря</option>
                        @foreach (PISBusinessLogic.ViewModels.UserViewModel user in ViewBag.Users)
                        {
                            if (@user.Role == 0)
                            {
                                <option value="@user.Id">@user.FIO</option>
                            }
                        }
                    </select>
                </div>
            </div>
        </p>
        <p>
            Месяц:
            <input type="month" name="month"  />
        </p>
    </div>
    <div class="col-sm-8">
        <input type="submit" value="Найти" class="btn btn-dark btn-sm" />
    </div>
</form>
@Html.ValidationSummary(true, "", new { @style = "color: black" })

@if (ViewBag.Contract != null)
{
    <table class="table">
        <tr>
            <td>Дата</td>
            <td>Библиотекарь</td>
            <td>Дата возврата</td>
            <td>Сумма, руб.</td>
            <td>Штраф</td>
            <td>Статус</td>
            <td>Читатель</td>
        </tr>
        @foreach (var r in ViewBag.Contract)
        {

                    <tr>
                        <td>@r.Date.ToShortDateString()</td>
                        <td>@r.LibrarianFIO</td>
                        <td>@r.DateReturn.ToShortDateString()</td>
                        <td>@r.Sum</td>
                        <td>@r.Fine</td>
                        <td>@r.ContractStatus</td>
                        <td>@r.ReaderFIO</td>
                    </tr>
        }
    </table>
}

PIS-master/PISCourseworkARMAccountant/Views/Accountant/ListOfLibrarian.cshtml
@model PISBusinessLogic.BindingModels.UserBindingModel
@{
    ViewData["Title"] = "Библиотекарь";
}

<div class="text-center text-black-50">
    <h1>Библиотекарь</h1>
</div>
<hr />
<form asp-controller="Accountant" asp-action="ListOfLibrarian" method="get">
    <div class="col-sm-8">
        Поиск библиотекаря<br />

        По личному коду:
        @Html.TextBoxFor(x => x.Id)
        <br />
        По фамилии:
        @Html.TextBoxFor(x => x.FIO)

        <input type="submit" value="Поиск" class="btn btn-dark btn-sm" />
    </div>
</form>
<table class="table">
    <tr>
        <td>Личный код</td>
        <td>ФИО</td>
        <td>Оклад,руб.</td>
        <td>Процент,%</td>
        <td>Комиссионные,руб.</td>
    </tr>


    @foreach (var user in ViewBag.Users)
    {
<tr>
    <td>@user.Id</td>
    <td>@user.FIO</td>
    <td>@user.Salary</td>
    <td>@user.ComissionPercent</td>
    <td>@user.Comission</td>
    <td>
        @Html.ActionLink("Контракт с библиотекарем(.docx)", "ContractLibrarian", "Report", new { id = @user.Id }, new { @class = "btn btn-dark btn-sm" })
    </td>
</tr>
    }

</table>

<form asp-controller="Report" asp-action="List" method="get">
    <div class="col-sm-8">
        <input type="submit" value="Список всех библиотекарей(.docx)" class="btn btn-dark btn-sm" id="save-docx" />
    </div>
</form>

<br/>

<table class="table">
    <div class="col-sm-8">
        <p> <strong> <a class="btn btn-dark btn-sm" href="/Accountant/ChangeCommission">Изменить процент комиссионных</a></strong></p>
    </div>
</table>

PIS-master/PISCourseworkARMAccountant/Views/Accountant/Report.cshtml
@{
    ViewData["Title"] = "Отчеты";
}

<div class="text-center text-black-50">
    <h3>Отчеты</h3>
</div>
<hr />
<p> <strong> <a class="btn btn-dark btn-sm" href="/Report/Chart">Диаграмма стоимость заключенных договоров по библиотекарям</a></strong></p>
<p> <strong> <a class="btn btn-dark btn-sm" href="/Report/LeadSalary">Ведомость заработной платы</a></strong></p>
<p> <strong> <a class="btn btn-dark btn-sm" href="/Report/DistributionSalary">Распределение зарплаты библиотекарей по месяцам</a></strong></p>
<p> <strong> <a class="btn btn-dark btn-sm" href="/Report/CheckLibrarian">Проверка отчета библиотекаря</a></strong></p>
<p> <strong> <a class="btn btn-dark btn-sm" href="/Report/BackUpToJson">Архив</a></strong></p>

PIS-master/PISCourseworkARMAccountant/Views/Accountant/Salary.cshtml
@model PISBusinessLogic.BindingModels.PaymentBindingModel

@{
    ViewData["Title"] = "Добавление зарплаты";
}
@using (Html.BeginForm("AddSalary", "Salary"))
{
    <div class="text-center text-black-50">
        <h3>Добавление зарплаты</h3>
    </div>
    <hr />
    <p>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Библиотекарь:</label>
            <div class="col-sm-4">
                <select class="custom-select custom-select-sm" name="Id" id="Id">
                    <option value="" selected disabled hidden>Выберите библиотекаря</option>
                    @foreach (PISBusinessLogic.ViewModels.UserViewModel user in ViewBag.Users)
                    {
                        if (@user.Role == 0)
                        {
                            <option value="@user.Id">@user.FIO</option>
                        }
                    }
                </select>
            </div>
        </div>
        <div class="col-sm-4">
            Дата:<br>
            <input type="date" name="date" />
        </div>

        <br />
    </p>
    <div class="col-sm-8">
        <input type="submit" value="Начислить" class="btn btn-dark btn-sm" />
    </div>
}
<br />
@Html.ValidationSummary(true, "", new { @style = "color: black" })
<form asp-controller="Salary" asp-action="SalaryAll">
    <div class="text-center text-black-50">
        <h3>Расчет суммарной стоимости зарплаты за год</h3>
    </div>
    <hr />
    <div class="col-sm-4">
        Введите год:<br>
        <input name="date" type="date" />
    </div>
    <br />
    <div class="col-sm-4">
        <input type="submit" value="Вычислить" class="btn btn-dark btn-sm" />
    </div>
    <br />
    <div class="col-sm-4">
        Сумма:
        @ViewBag.Sum
    </div>
</form>